branch-defaults:
  master:
    environment: CarBynetUserService01
environment-defaults:
  CarBynetUserService01:
    branch: null
    repository: null
global:
  application_name: Meny-test
  default_ec2_keyname: staging-key_v1
  default_platform: arn:aws:elasticbeanstalk:eu-west-1::platform/Java 8 running on
    64bit Amazon Linux/2.7.6
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
